/* eslint-disable import/prefer-default-export */
export const cardsData = [
  {
    name: 'tournichette project',
    logo: '/tournichette-logo.svg',
    cardText: [
      'Eshop avec backOffice',
      'React.js',
      'Redux, Redux toolkit',
      'SASS, Framer Motion',
      'Serveur de paiement Stripe',
    ],
    popupText: [
      'Projet de fin d\'étude avec une équipe de 4 développeurs.',
      'Product owner et lead Dev Front.',
      '',
      '',
      'Mise en place d\'un cahier des charges, wireframe, MCD...',
      'Respect de la chartre graphique du client et des demandes spécifiques à leur activité.',
      '',
      '',
      'BackOffice et API en PHP (symfony).',
      'Créations des fiches produits, gestions des clients, génération des carnets de récolte en PDF, données comptables.',
      'Mailing.',
      '',
      '',
      'Front office en React.js.',
      'Animations Framer Motion.',
      'Gestion du State via redux, requête Axios et AsyncThunk middleware.',
      'interface de paiement Stripe.',
      '',
      '',
      'La Tournichette a un système de vente périodique atypique, le site a donc été cloné pour les besoins de la présentation.',
    ],
    code: 'https://github.com/VincentVanN/tournichette-project-front',
    codeBack: 'https://github.com/VincentVanN/tournichette-project-back',
    link: 'https://eshop.vann-dev.com',
  },
  {
    name: 'Portfolio',
    logo: '/portfolio-logo.png',
    cardText: [
      'React.js',
      'Framer Motion',
      'Particle image',
      'API maps',
    ],
    code: 'https://github.com/VincentVanN/portfolio',
  },
  {
    name: 'tetris game react',
    logo: '/tetris-logo.svg',
    cardText: [
      'React.js',
      'Framer Motion',
      'Algorythme et gestion de l\'audio js vanilla',
      'TS-particles',
    ],
    code: 'https://github.com/VincentVanN/tetris-project',
    link: 'https://tetris.vann-dev.com',
  },
  {
    name: 'Padlocker',
    logo: '/particle-logo.png',
    cardText: [
      'Gestionnaire et générateur de mots de passe dynamique',
      'Extension Chrome',
      'React.js',
      'Redux/toolKit',
      'Firebase/Firestore',
    ],
    popupText: [
      'PadLocker génère et enregistre vos mots de passe.',
      '',
      '',
      'Localise L\'url de navigation. Si l\'url est connue, il vous restitue votre mot de passe.',
      'Si l\'url n\'est pas enregistré, il vous génère un mot de passe sécurisé aléatoire de 16 caractères composé de minuscules, majuscules, chiffres et symboles.',
      'Vous pouvez enregistrer vos propres mots de passe, ainsi que les modifier.',
      '',
      '',
      'Un seul mot de passe à retenir, celui de votre compte Google.',
      'Vos mots de passe sont chiffrés AES de bout en bout. Seul vous y avez accès.',
      '',
      '',
      'L\'utilisation de PadLocker est gratuite, et requiert obligatoirement un compte Google valide et authentifié.',
    ],
    code: 'https://github.com/VincentVanN/padlock',
  },
  {
    name: 'application meteo',
    logo: '/meteo-logo.svg',
    cardText: [
      'Vue.js',
      'Tailwind CSS',
      'API Open Weather',
      'API MapBox',
    ],
    code: 'https://github.com/VincentVanN/weather',
    link: 'https://meteo.vann-dev.com',
  },
  {
    name: 'particles text javascript',
    logo: '/particle-logo.png',
    cardText: [
      'Javascript vanilla',
    ],
    code: 'https://github.com/VincentVanN/customParticles',
    link: 'https://particles.vann-dev.com',
  },
];
